server:
  port: 9092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/echis_data_1
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#
#  file:
#    name: myapp.log
#    path: /src/main/logs/